#!/bin/sh
if [ "$STAGE_NAME" = "Deploy" ]; then
  # Run your deploy command here
  echo "Running deploy command..."
  docker run -p 4200:4200 weather-app:$IMAGE_VERSION ng serve --host 0.0.0.0 --port 4200
else
  echo "Pipeline stage is not deploy; skipping command execution."
fi

#test trigger