---
- name: Update yum and install Docker
  yum:
    name: docker
    state: present
  become: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes
  become: true

- name: Show Docker version
  command: docker --version
  become: true
