on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  otel-cicd-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: corentinmusard/otel-cicd-action@v2
        with:
          otlpEndpoint: http://35.205.152.87:4317/
          otlpHeaders: header=test
          githubToken: ${{ secrets.token  }}
          runId: ${{ github.event.workflow_run.id }}
