on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  otel-cicd-actions:
    runs-on: ubuntu-latest
    steps:
      # - uses: corentinmusard/otel-cicd-action@v2
      #   with:
      #     otlpEndpoint: http://35.205.152.87:4317/
      #     otlpHeaders: ""
      #     githubToken: ${{ secrets.token  }}
      #     runId: ${{ github.event.workflow_run.id }}
      - name: Export Workflow Trace
        uses: inception-health/otel-export-trace-action@latest
        with:
          otlpEndpoint: "http://34.79.80.194:4318/v1/traces"
          otlpHeaders: ""
          githubToken: ${{ secrets.token }}
          runId: ${{ github.event.workflow_run.id }}
