name: "Test"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo message 1
        run: echo "This is message 2"

      - name: Sleep for 1 seconds
        run: sleep 1

      - name: Echo message 2
        run: echo "This is message 2"

      - name: Sleep for 1 seconds
        run: sleep 1

      - name: Echo message 3
        run: echo "This is message 3"
