name: "Test"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo message 1
        run: echo "This is message 1"

      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Echo message 2
        run: echo "This is message 2"

      - name: Sleep for 3 seconds
        run: sleep 3

      - name: Echo message 3
        run: echo "This is message 3"

      # - name: Export workflow
      #   uses: corentinmusard/otel-cicd-action@v2
      #   with:
      #     otlpEndpoint: http://35.205.152.8:4318/
      #     otlpHeaders: header=test
      #     githubToken: ${{ secrets.token }}
